local:
  config:
    seata:
      role: "consumer"
    mysql:
      host: "192.168.0.11"
      port: 3307
      username: "root"
      password: "root"
      database: "seata-storage"
    nacos:
      host: "127.0.0.1"
      port: 8848