server:
  port: 7929

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: "storage-seata-in-action"
  profiles:
    active: dev
  datasource:
    type: "com.alibaba.druid.pool.DruidDataSource"
    druid:
      driver-class-name: "com.mysql.cj.jdbc.Driver"
      url: "jdbc:mysql://${local.config.mysql.host}:${local.config.mysql.port}/${local.config.mysql.database}?useUnicode=true&characterEncoding=UTF-8"
      username: ${local.config.mysql.username}
      password: ${local.config.mysql.password}
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    nacos:
      discovery:
        server-addr: "${local.config.nacos.host}:${local.config.nacos.port}"
        password: nacos
        username: nacos
      config:
        server-addr: "${local.config.nacos.host}:${local.config.nacos.port}"
        password: nacos
        username: nacos
        type: yaml
    alibaba:
      seata:
        tx-service-group: changqing

seata:
  registry:
    type: nacos
    nacos:
      server-addr: "${local.config.nacos.host}:${local.config.nacos.port}"
      application: seata-server
      password: nacos
      username: nacos
      group: SEATA_GROUP
  config:
    type: nacos
    nacos:
      server-addr: "${local.config.nacos.host}:${local.config.nacos.port}"
      password: nacos
      username: nacos
      group: SEATA_GROUP

ribbon:
  nacos:
    enabled: false

mybatis-plus:
  configuration:
    cache-enabled: false
    jdbc-type-for-null: 'null'
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true
  global-config:
    db-config:
      id-type: id_worker
      table-prefix: sys_
      capital-mode: true
    db-column-underline: true
    field-strategy: 2
    refresh-mapper: true
  check-config-location: true
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.photowey.spring.cloud.alibaba.seata.storage.in.action.domain.entity

#nacos:
#  discovery:
#    server-addr: "${local.config.nacos.host}:${local.config.nacos.port}"
#  config:
#    auto-refresh: true
#    bootstrap:
#      enable: true
#    config-long-poll-timeout: 46000
#    config-retry-time: 2333
#    data-id: ${spring.application.name}
#    enable-remote-sync-config: true
#    group: DEFAULT_GROUP
#    max-retry: 10
#    password: nacos
#    username: nacos
#    remote-first: true
#    server-addr: "${local.config.nacos.host}:${local.config.nacos.port}"
#    type: yaml

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  level:
    root: info
  pattern:
    console: '%red(%d{yyyy-MM-dd HH:mm:ss.SSS}) %red([${spring.application.name}]) %green([%thread]) %highlight(%-5level) %boldMagenta(%logger) - %cyan(%msg%n)'