local:
  config:
    uaa:
      issuer: http://localhost:4070

spring:
  security:
    oauth2:
      client:
        registration:
          photowey:
            client-id: photowey
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            #redirect-uri: "http://127.0.0.1:8081/hello/privatekey"
            authorization-grant-type: authorization_code
            client-authentication-method: private_key_jwt
            scope: userinfo,openid
        provider:
          photowey:
            issuer-uri: ${local.config.uaa.issuer}
