spring:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.0.11:8848
        username: nacos
        password: nacos

paradise:
  config:
    security:
      user:
        name: paradise
        password: paradise
    eureka:
      hostname: 192.168.1.11
      port: 8761
    gateway:
      port: 7777
    auth:
      host: 192.168.1.6
      port: 9000