server:
  port: 7923
  tomcat:
    uri-encoding: UTF-8

spring:
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
  application:
    name: "sqlite-in-action"
  profiles:
    active: dev
  datasource:
    url: "jdbc:sqlite:D:\\software\\sqlite\\db\\hello.sqlite.db"
    username:
    password:
    driver-class-name: org.sqlite.JDBC

#mybatis
mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml
  typeAliasesPackage: com.photowey.sqlite.in.action.domain.entity
  global-config:
    db-config:
      id-type: ID_WORKER
      field-strategy: NOT_NULL
      column-underline: true
      logic-delete-value: -1
      logic-not-delete-value: 0
    banner: false
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
    jdbc-type-for-null: 'null'

logging:
  level:
    root: info
  pattern:
    console: '%red(%d{yyyy-MM-dd HH:mm:ss.SSS}) %red([${spring.application.name}]) %green([%thread]) %highlight(%-5level) %boldMagenta(%logger) - %cyan(%msg%n)'