management:
  endpoint:
    shutdown:
      enabled: true
    health:
      show-details: ALWAYS
  endpoints:
    web:
      exposure:
        # autoconfig & trace No mapping
        # include: [health,info,beans,env,configprops,mappings,metrics]
        include: "*"

# custom the /actuator/info endpoint
info:
  app:
    name: @project.artifactId@
    encoding: @project.build.sourceEncoding@
    java:
      source: @java.version@
      target: @java.version@
  evn:
    active: ${spring.profiles.active}

local:
  config:
    mysql:
      ds0:
        host: "192.168.1.11"
        port: 3307
        username: "root"
        password: "root"
        database: "shardingsphere-in-action"
      ds1:
        host: "192.168.1.11"
        port: 3308
        username: "root"
        password: "root"
        database: "shardingsphere-in-action"