local:
  config:
    seata:
      role: "producer"
    mysql:
      host: "192.168.1.11"
      port: 3307
      username: "root"
      password: "root"
      database: "producer-seata-in-action"
    nacos:
      host: "127.0.0.1"
      port: 8848