spring:
  security:
    oauth2:
      client:
        registration:
          photowey:
            client-id: photowey
            client-secret: photowey
            redirect-uri: "http://127.0.0.1:${server.port}/login/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_basic
            scope: message.read,message.write,openid,userinfo
        provider:
          photowey:
            issuer-uri: http://localhost:9000
