server:
  port: 7923
  tomcat:
    uri-encoding: UTF-8

spring:
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
  application:
    name: "sqlmap-in-action"
  profiles:
    active: dev

logging:
  level:
    root: info
  pattern:
    console: '%red(%d{yyyy-MM-dd HH:mm:ss.SSS}) %red([${spring.application.name}]) %green([%thread]) %highlight(%-5level) %boldMagenta(%logger) - %cyan(%msg%n)'