local:
  config:
    nacos:
      host: "127.0.0.1"
      port: 8848

nacos:
  config:
    auto-refresh: true
    bootstrap:
      enable: true
    config-long-poll-timeout: 46000
    config-retry-time: 2333
    data-id: nacos-in-action
    enable-remote-sync-config: true
    group: DEFAULT_GROUP
    max-retry: 10
    password: nacos
    username: nacos
    remote-first: true
    server-addr: "${local.config.nacos.host}:${local.config.nacos.port}"
    type: yaml

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'