server:
  port: 7923
  tomcat:
    uri-encoding: UTF-8

spring:
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
  application:
    name: "${local.config.spring.name}"
  profiles:
    active: dev

xxl:
  job:
    accessToken: ""
    admin:
      addresses: "http://${local.config.xxljob.host}:${local.config.xxljob.port}/xxl-job-admin"
    executor:
      address: "${xxl.job.executor.ip}:${xxl.job.executor.port}"
      app-name: "${local.config.spring.name}"
      ip: "192.168.217.1"
      log-path: "logs/jobs/handler"
      log-retention-days: 30
      port: 9999

knife4j:
  enable: true
  setting:
    language: zh-CN
    enableFooter: false
    enableFooterCustom: true
    footerCustomContent: Apache License 2.0 | Copyright  2021-[photowey](https://github.com/photowey/the-way-to-java)
  production: false

logging:
  level:
    root: info
  pattern:
    console: '%red(%d{yyyy-MM-dd HH:mm:ss.SSS}) %red([${spring.application.name}]) %green([%thread]) %highlight(%-5level) %boldMagenta(%logger) - %cyan(%msg%n)'